package OODJ_Assignment;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Admin_Menu extends javax.swing.JFrame {
    ArrayList<String> id = new ArrayList();
    ArrayList<String> name = new ArrayList();
    ArrayList<String> Model = new ArrayList();
    ArrayList<String> type = new ArrayList();
    ArrayList<String> seats = new ArrayList();
    ArrayList<String> transmission = new ArrayList();
    ArrayList<String> price = new ArrayList();
    ArrayList<String> status = new ArrayList();
    ArrayList<String> cname = new ArrayList();
    ArrayList<String> phone = new ArrayList();
    ArrayList<String> gender = new ArrayList();
    ArrayList<String> country = new ArrayList();
    ArrayList<String> email = new ArrayList();
    ArrayList<String> passport = new ArrayList();
    ArrayList<String> username = new ArrayList();
    ArrayList<String> pass = new ArrayList();
    ArrayList<String> bUser = new ArrayList();
    ArrayList<String> bID = new ArrayList();
    ArrayList<String> bName = new ArrayList();
    ArrayList<String> bModel = new ArrayList();
    ArrayList<String> bDate = new ArrayList();
    ArrayList<String> bTotal = new ArrayList();
    ArrayList<String> bPay = new ArrayList();
    ArrayList<String> bConf = new ArrayList();
    /**
     * Creates new form Admin_Homepage
     */
    public Admin_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CarsT = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameT = new javax.swing.JTextField();
        PriceT = new javax.swing.JTextField();
        TypeC = new javax.swing.JComboBox<>();
        seatsC = new javax.swing.JComboBox<>();
        TransmissionC = new javax.swing.JComboBox<>();
        StatusC = new javax.swing.JComboBox<>();
        AddB = new javax.swing.JToggleButton();
        EditB = new javax.swing.JToggleButton();
        deleteB = new javax.swing.JToggleButton();
        ModelT = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cusT = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cusEmailT = new javax.swing.JTextField();
        cusGenderC = new javax.swing.JComboBox<>();
        EditB1 = new javax.swing.JToggleButton();
        deleteB1 = new javax.swing.JToggleButton();
        cusPhoneT = new javax.swing.JTextField();
        cusNameT1 = new javax.swing.JTextField();
        cusCountryT = new javax.swing.JTextField();
        cusPassportT = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cusPassT = new javax.swing.JTextField();
        cusUserT = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        book = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Car Name:");

        CarsT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        CarsT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarsTMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CarsTMousePressed(evt);
            }
        });
        CarsT.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CarsTPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(CarsT);

        jLabel4.setText("Model:");

        jLabel5.setText("Type:");

        jLabel6.setText("Seats:");

        jLabel7.setText("Transmission:");

        jLabel8.setText("Price/hour:");

        jLabel9.setText("Status:");

        TypeC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hatchback", "SUV", "Sedan", "MPV", "Economy" }));

        seatsC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "5", "6", "7", "8", "9", "11" }));

        TransmissionC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automatic", "Manual" }));

        StatusC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Booked" }));

        AddB.setBackground(new java.awt.Color(153, 255, 153));
        AddB.setText("ADD");
        AddB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBActionPerformed(evt);
            }
        });

        EditB.setBackground(new java.awt.Color(153, 255, 153));
        EditB.setText("EDIT");
        EditB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBActionPerformed(evt);
            }
        });

        deleteB.setBackground(new java.awt.Color(153, 255, 153));
        deleteB.setText("DELETE");
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(25, 25, 25))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameT)
                            .addComponent(ModelT)
                            .addComponent(TypeC, 0, 132, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TransmissionC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatsC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(119, 119, 119)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AddB, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EditB, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PriceT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatusC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(119, 119, 119)
                                .addComponent(deleteB, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatsC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(nameT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PriceT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ModelT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StatusC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(TypeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(EditB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TransmissionC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(AddB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteB, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cars", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel2.setText("Name:");

        cusT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        cusT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cusTMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cusTMousePressed(evt);
            }
        });
        cusT.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cusTPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(cusT);

        jLabel10.setText("Phone Number:");

        jLabel11.setText("Gender:");

        jLabel12.setText("Country:");

        jLabel13.setText("Email:");

        jLabel14.setText("Passport:");

        cusGenderC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        EditB1.setText("EDIT");
        EditB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditB1ActionPerformed(evt);
            }
        });

        deleteB1.setText("DELETE");
        deleteB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteB1ActionPerformed(evt);
            }
        });

        cusPassportT.setText("Passport:");

        jLabel17.setText("Password:");

        cusUserT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusUserTActionPerformed(evt);
            }
        });

        jLabel15.setText("UserName:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2)
                            .addComponent(jLabel17)
                            .addComponent(jLabel11))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusGenderC, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusPhoneT, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusNameT1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusPassT, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(25, 25, 25)
                                        .addComponent(cusCountryT, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel14)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cusPassportT)
                                            .addComponent(cusEmailT, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cusUserT, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(EditB1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteB1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2)
                            .addComponent(cusCountryT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusNameT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(cusEmailT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cusPhoneT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cusPassT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel14)
                                    .addComponent(cusPassportT))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cusGenderC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addComponent(cusUserT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(EditB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(17, 17, 17)))
                        .addComponent(deleteB1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Customers", jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        book.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(book);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("MAIN MENU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bookings", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBActionPerformed
        int x = id.size()+1;
        id.add(Integer.toString(x));
        name.add(nameT.getText());
        Model.add(ModelT.getText());
        type.add(TypeC.getSelectedItem().toString());
        seats.add(seatsC.getSelectedItem().toString());
        transmission.add(TransmissionC.getSelectedItem().toString());
        price.add(PriceT.getText());
        status.add(StatusC.getSelectedItem().toString());
        try(FileWriter fw = new FileWriter("Cars.txt");) {
            fw.write("ID,Name,Model,Type,Seats,Transmission,Price,Status\n");
            for (int i=0;i<name.size();i++){
                fw.write(id.get(i)+","+this.name.get(i)+","+this.Model.get(i)+","+this.type.get(i)+","+this.seats.get(i)+","+this.transmission.get(i)+","+this.price.get(i)+","+this.status.get(i)+"\n");
            }
            fw.close();
            JOptionPane.showMessageDialog(null,"Success!!");
         }
        catch (IOException e) {
            System.out.println("Incorrect File Path");
         }
        CarsT.setModel(new DefaultTableModel());
        
    }//GEN-LAST:event_AddBActionPerformed

    private void EditBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBActionPerformed
        name.set(CarsT.getSelectedRow(), nameT.getText());
        Model.set(CarsT.getSelectedRow(), ModelT.getText());
        type.set(CarsT.getSelectedRow(), TypeC.getSelectedItem().toString());
        seats.set(CarsT.getSelectedRow(), seatsC.getSelectedItem().toString());
        transmission.set(CarsT.getSelectedRow(), TransmissionC.getSelectedItem().toString());
        price.set(CarsT.getSelectedRow(), PriceT.getText());
        status.set(CarsT.getSelectedRow(), StatusC.getSelectedItem().toString());
        try(FileWriter fw = new FileWriter("Cars.txt");) {
            fw.write("ID,Name,Model,Type,Seats,Transmission,Price,Status\n");
            for (int i=0;i<name.size();i++){
                fw.write(id.get(i)+","+this.name.get(i)+","+this.Model.get(i)+","+this.type.get(i)+","+this.seats.get(i)+","+this.transmission.get(i)+","+this.price.get(i)+","+this.status.get(i)+"\n");
            }
            fw.close();
            JOptionPane.showMessageDialog(null,"Success!!");
         }
        catch (IOException e) {
            System.out.println("Incorrect File Path");
         }
        CarsT.setModel(new DefaultTableModel());
    }//GEN-LAST:event_EditBActionPerformed

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed
        for(int i=0;i<id.size();i++){
            if(i>CarsT.getSelectedRow()){
                id.set(i,Integer.toString(i));
            }
        } 
        id.remove(CarsT.getSelectedRow());
        name.remove(CarsT.getSelectedRow());
        Model.remove(CarsT.getSelectedRow());
        type.remove(CarsT.getSelectedRow());
        seats.remove(CarsT.getSelectedRow());
        transmission.remove(CarsT.getSelectedRow());
        price.remove(CarsT.getSelectedRow());
        status.remove(CarsT.getSelectedRow());
        try(FileWriter fw = new FileWriter("Cars.txt");) {
            fw.write("ID,Name,Model,Type,Seats,Transmission,Price,Status\n");
            for (int i=0;i<name.size();i++){
                fw.write(id.get(i)+","+this.name.get(i)+","+this.Model.get(i)+","+this.type.get(i)+","+this.seats.get(i)+","+this.transmission.get(i)+","+this.price.get(i)+","+this.status.get(i)+"\n");
            }
            fw.close();
            JOptionPane.showMessageDialog(null,"Success!!");
         }
        catch (IOException e) {
            System.out.println("Incorrect File Path");
         }
    }//GEN-LAST:event_deleteBActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        CarsT.setModel(new DefaultTableModel());
        cusT.setModel(new DefaultTableModel());
        book.setModel(new DefaultTableModel());
        id.clear();
        name.clear();
        Model.clear();
        type.clear();
        seats.clear();
        transmission.clear();
        price.clear();
        cname.clear();
        phone.clear();
        gender.clear();
        country.clear();
        email.clear();
        passport.clear();
        username.clear();
        pass.clear();
        bUser.clear();
        bID.clear();
        bName.clear();
        bModel.clear();
        bDate.clear();
        bTotal.clear();
        bPay.clear();
        bConf.clear();
        try {
                BufferedReader br = new BufferedReader(new FileReader("Cars.txt"));
                String firstLine = br.readLine().trim();
                String[] columnsName = firstLine.split(",");
                DefaultTableModel model = (DefaultTableModel) CarsT.getModel();
                model.setColumnIdentifiers(columnsName);
                Object[] tableLines = br.lines().toArray();
                for (int i = 0; i < tableLines.length; i++) {
                    String line = tableLines[i].toString().trim();
                    String[] dataRow = line.split(",");
                    id.add(dataRow[0]);
                    name.add(dataRow[1]);
                    Model.add(dataRow[2]);
                    type.add(dataRow[3]);
                    seats.add(dataRow[4]);
                    transmission.add(dataRow[5]);
                    price.add(dataRow[6]);
                    status.add(dataRow[7]);
                    model.addRow(dataRow);
                }

            } catch (IOException e) {
                System.out.println("Incorrect File");
            }
        try {
                BufferedReader br = new BufferedReader(new FileReader("Customer.txt"));
                String firstLine = br.readLine().trim();
                String[] columnsName = firstLine.split(",");
                DefaultTableModel model = (DefaultTableModel) cusT.getModel();
                model.setColumnIdentifiers(columnsName);
                Object[] tableLines = br.lines().toArray();
                for (int i = 0; i < tableLines.length; i++) {
                    String line = tableLines[i].toString().trim();
                    String[] dataRow = line.split(",");
                    cname.add(dataRow[0]);
                    phone.add(dataRow[1]);
                    gender.add(dataRow[2]);
                    country.add(dataRow[3]);
                    email.add(dataRow[4]);
                    passport.add(dataRow[5]);
                    username.add(dataRow[6]);
                    pass.add(dataRow[7]);
                    model.addRow(dataRow);
                }

            } catch (IOException e) {
                System.out.println("Incorrect File");
            }
        try {
                BufferedReader br = new BufferedReader(new FileReader("booking.txt"));
                String firstLine = br.readLine().trim();
                String[] columnsName = firstLine.split(",");
                DefaultTableModel model = (DefaultTableModel) book.getModel();
                model.setColumnIdentifiers(columnsName);
                Object[] tableLines = br.lines().toArray();
                for (int i = 0; i < tableLines.length; i++) {
                    String line = tableLines[i].toString().trim();
                    String[] dataRow = line.split(",");
                    bUser.add(dataRow[0]);
                    bID.add(dataRow[1]);
                    bName.add(dataRow[2]);
                    bModel.add(dataRow[3]);
                    bDate.add(dataRow[4]);
                    bTotal.add(dataRow[5]);
                    bPay.add(dataRow[6]);
                    bConf.add(dataRow[7]);
                    model.addRow(dataRow);
                }

            } catch (IOException e) {
                System.out.println("Incorrect File");
            }
    }//GEN-LAST:event_formWindowActivated

    private void CarsTPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CarsTPropertyChange

    }//GEN-LAST:event_CarsTPropertyChange

    private void CarsTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarsTMouseClicked
        
    }//GEN-LAST:event_CarsTMouseClicked

    private void CarsTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarsTMousePressed
        
        nameT.setText(name.get(CarsT.getSelectedRow()));
        ModelT.setText(Model.get(CarsT.getSelectedRow()));
        PriceT.setText(price.get(CarsT.getSelectedRow()));
        StatusC.setSelectedItem(status.get(CarsT.getSelectedRow()));
        TransmissionC.setSelectedItem(transmission.get(CarsT.getSelectedRow()));
        seatsC.setSelectedItem(seats.get(CarsT.getSelectedRow()));
        TypeC.setSelectedItem(type.get(CarsT.getSelectedRow()));
    }//GEN-LAST:event_CarsTMousePressed

    private void cusTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cusTMouseClicked

    private void cusTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cusTMousePressed

        cusNameT1.setText(cname.get(cusT.getSelectedRow()));
        cusPhoneT.setText(phone.get(cusT.getSelectedRow()));
        cusCountryT.setText(country.get(cusT.getSelectedRow()));
        cusEmailT.setText(email.get(cusT.getSelectedRow()));
        cusPassportT.setText(passport.get(cusT.getSelectedRow()));
        cusUserT.setText(username.get(cusT.getSelectedRow()));
        cusPassT.setText(pass.get(cusT.getSelectedRow()));
        cusGenderC.setSelectedItem(gender.get(cusT.getSelectedRow()));
        
    }//GEN-LAST:event_cusTMousePressed

    private void cusTPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cusTPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cusTPropertyChange

    private void EditB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditB1ActionPerformed
        cname.set(cusT.getSelectedRow(), cusNameT1.getText());
        phone.set(cusT.getSelectedRow(), cusPhoneT.getText());
        country.set(cusT.getSelectedRow(), cusCountryT.getText());
        email.set(cusT.getSelectedRow(), cusEmailT.getText());
        passport.set(cusT.getSelectedRow(), cusPassportT.getText());
        username.set(cusT.getSelectedRow(), cusUserT.getText());
        pass.set(cusT.getSelectedRow(), cusPassT.getText());
        gender.set(cusT.getSelectedRow(), cusGenderC.getSelectedItem().toString());
        try(FileWriter fw = new FileWriter("Customer.txt");) {
            fw.write("Name,Phone Number,Gender,Country,Email,Passport,Username,Passwords\n");
            for (int i=0;i<cname.size();i++){
                fw.write(cname.get(i)+","+this.phone.get(i)+","+this.gender.get(i)+","+this.country.get(i)+","+this.email.get(i)+","+this.passport.get(i)+","+this.username.get(i)+","+this.pass.get(i)+"\n");
            }
            fw.close();
            JOptionPane.showMessageDialog(null,"Success!!");
         }
        catch (IOException e) {
            System.out.println("Incorrect File Path");
         }
    }//GEN-LAST:event_EditB1ActionPerformed

    private void deleteB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteB1ActionPerformed
        cname.remove(cusT.getSelectedRow());
        phone.remove(cusT.getSelectedRow());
        gender.remove(cusT.getSelectedRow());
        country.remove(cusT.getSelectedRow());
        email.remove(cusT.getSelectedRow());
        passport.remove(cusT.getSelectedRow());
        username.remove(cusT.getSelectedRow());
        pass.remove(cusT.getSelectedRow());
        try(FileWriter fw = new FileWriter("Customer.txt");) {
            fw.write("Name,Phone Number,Gender,Country,Email,Passport,Username,Passwords\n");
            for (int i=0;i<cname.size();i++){
                fw.write(cname.get(i)+","+this.phone.get(i)+","+this.gender.get(i)+","+this.country.get(i)+","+this.email.get(i)+","+this.passport.get(i)+","+this.username.get(i)+","+this.pass.get(i)+"\n");
            }
            fw.close();
         }
        catch (IOException e) {
            System.out.println("Incorrect File Path");
         }
        try(FileWriter fw = new FileWriter("credentials.txt");) {
            fw.write("1,admin123\n");
            fw.write("732a8,admin123\n");
            fw.write("1dbe4,admin123\n");
            for (int i=0;i<username.size();i++){
                fw.write(this.username.get(i)+","+this.pass.get(i)+"\n");
            }
            fw.close();
            JOptionPane.showMessageDialog(null,"Success!!");
         }
        catch (IOException e) {
            System.out.println("Incorrect File Path");
         }
    }//GEN-LAST:event_deleteB1ActionPerformed

    private void cusUserTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusUserTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusUserTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        ArrayList<String> bUser = new ArrayList();
//    ArrayList<String> bID = new ArrayList();
//    ArrayList<String> bName = new ArrayList();
//    ArrayList<String> bModel = new ArrayList();
//    ArrayList<String> bDate = new ArrayList();
//    ArrayList<String> bTotal = new ArrayList();
//    ArrayList<String> bPay = new ArrayList();
//    ArrayList<String> bConf = new ArrayList();

        bConf.set(book.getSelectedRow(),"Confirmed");
        try(FileWriter fw = new FileWriter("booking.txt");) {
            fw.write("USERNAME,CAR ID,CARNAME,CARMODEL,DATE,TOTAL PRICE,PAYMENT,CONFIRMATION\n");
            for (int i=0;i<bUser.size();i++){
                fw.write(bUser.get(i)+","+this.bID.get(i)+","+this.bName.get(i)+","+this.bModel.get(i)+","+this.bDate.get(i)+","+this.bTotal.get(i)+","+this.bPay.get(i)+","+this.bConf.get(i)+"\n");
            }
            fw.close();
            JOptionPane.showMessageDialog(null,"Success!!");
         }
        catch (IOException e) {
            System.out.println("Incorrect File Path");
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainMenu a = new MainMenu();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AddB;
    private javax.swing.JTable CarsT;
    private javax.swing.JToggleButton EditB;
    private javax.swing.JToggleButton EditB1;
    private javax.swing.JTextField ModelT;
    private javax.swing.JTextField PriceT;
    private javax.swing.JComboBox<String> StatusC;
    private javax.swing.JComboBox<String> TransmissionC;
    private javax.swing.JComboBox<String> TypeC;
    private javax.swing.JTable book;
    private javax.swing.JTextField cusCountryT;
    private javax.swing.JTextField cusEmailT;
    private javax.swing.JComboBox<String> cusGenderC;
    private javax.swing.JTextField cusNameT1;
    private javax.swing.JTextField cusPassT;
    private javax.swing.JLabel cusPassportT;
    private javax.swing.JTextField cusPhoneT;
    private javax.swing.JTable cusT;
    private javax.swing.JTextField cusUserT;
    private javax.swing.JToggleButton deleteB;
    private javax.swing.JToggleButton deleteB1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameT;
    private javax.swing.JComboBox<String> seatsC;
    // End of variables declaration//GEN-END:variables
}
